### PR TITLE
Add more decompression targets to decompress_target

### PR DESCRIPTION
**Pull request by viniul**
This commit adds more decompression targets to decompress_target.c. The target function is chosen based on the first byte of the data given by libfuzzer.

### CODE REVIEW

**Comment by viniul** [comment]
This new harness finds a crash in lzo1f_decompress_safe: 

==17==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020000008d2 at pc 0x0000005c0f00 bp 0x7ffd7a6a0830 sp 0x7ffd7a6a0828
READ of size 1 at 0x6020000008d2 thread T0
SCARINESS: 12 (1-byte-read-heap-buffer-overflow)
    #0 0x5c0eff in lzo1f_decompress_safe /src/lzo-2.10/src/lzo1f_d.ch:112:30

**Comment by bshastry** [comment]
Thanks @viniul 

This PR increases number of instrumented branches from ~119 to ~478 so by close to 400% :-)

**Comment by viniul** [comment]
Great! Next step would be to add other targets to compress_target?

**Comment by bshastry** [comment]
I think so. I'm fixing a minor bug with the PR which was that 1x was getting counted twice and 1c was getting left out due to dead code.

**Pull request merged**
